<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="MAIN" Id="{3f11ceaa-009a-4b5e-9a63-7b2c8a282994}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	sad: DINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[sad := 1 +sad;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>