<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="MAIN" Id="{c05d75f6-1e14-47e5-98de-612ecc680255}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	asd: BOOL;
	doubl: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[asd := doubl;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>