<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="MAIN" Id="{b2c178c7-064e-4039-923c-873a2e37011c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	test: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[test := 1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>